### ISSUE TITLE
6 != 5

### ISSUE THREAD

**Issue by lolNotFitz** [du-cki/Kanapy#2]
In cogs/username.py on line 37 you're checking if len(q['robloxUser']) > 5 when you should be checking if len(q['robloxUser']) >= 5 so that the max number of usernames is 5, not 6.

**Comment by du-cki** [comment]
Ah yes! Sorry, will be fixed next commit!

**Comment by Kagetasu** [comment]
> In cogs/username.py on line 37 you're checking if len(q['robloxUser']) > 5 when you should be checking if len(q['robloxUser']) >= 5 so that the max number of usernames is 5, not 6.

🤓

**Comment by Kagetasu** [comment]
> In cogs/username.py on line 37 you're checking if len(q['robloxUser']) > 5 when you should be checking if len(q['robloxUser']) >= 5 so that the max number of usernames is 5, not 6.

🤓
